### ISSUE TITLE
M73

### ISSUE THREAD

**Issue by wigw** [ichekanov/PrusaSlicer_time_converter#1]
Hello.
I really liked your plugin. I would like you to write another version of the instance, namely, leave everything as it is, plus leave M73. 
OctoPi complains about the lack of M73. 
Thanks

**Comment by ichekanov** [comment]
Hi!

`M73` command is inserted to gcode by PrusaSlicer itself. My script only replaces this command to Marlin-suitable `M117`. If you need `M73` in your gcode, you simply don't have to run this script.
To enable `M73` commands insertion, you should tick the following inside PrusaSlicer: `Printer settings` -> `General` -> `Supports remaining time`. After enabling it you will get gcode with `M73` commands.

I think I understood you correctly. If not, please ask again.

**Comment by wigw** [comment]
No. I need both M118 and M73.
I have attached my modification of your script.
[time_converter.txt](https://github.com/ichekanov/PrusaSlicer_time_converter/files/9696899/time_converter.txt)

**Comment by wigw** [comment]
I need M118 for TFT and M73 for OctoPi pagins
https://github.com/bigtreetech/BIGTREETECH-TouchScreenFirmware#printing-from-remote-host

**Comment by ichekanov** [comment]
Okay. Your modification of the script still does not save the `M73` command. Also, `M73` command stores only minutes left, so it is useless to count seconds — it always will be zero.
So, my idea is: [time_converter.txt](https://github.com/ichekanov/PrusaSlicer_time_converter/files/9697132/time_converter.txt). If it is what you wanted, please test it on your setup. If everything is correct, I can upload it to the repository.

**Comment by wigw** [comment]
This is very good, but I do not have enough M73
I ask like in the example
Example:
M73 P0 R74
M118 A1 P0 action:notification Time Left 01h14m01s

**Comment by ichekanov** [comment]
Do you want to display every passed second using `M118` command?

**Comment by ichekanov** [comment]
I've got your point: you want to extrapolate remaining time to calculate seconds. I will try implement this in the near future, but not today :)

**Comment by wigw** [comment]
No, I just want to have 2 deadlines.
M73
M118

**Comment by ichekanov** [comment]
May you text me via [telegram](https://t.me/chekanov_ivan)?

**Comment by wigw** [comment]
Thanks a lot. 
A lot of work has been done. 
Got good code. 
Plugin for PrusaSlicer, there are M73 and M118.
